name: Push Helm chart to ACR

on:
    push:
        branches:
            - master

env:
    HELM_EXPERIMENTAL_OCI: 1
    HELM_VERSION_TO_INSTALL: 3.5.0
    ACR_NAME: holon
    ACR_REPO_NAME: ${{ secrets.AZURE_URL }}/hallo-azure-helmchart

jobs:
    build:
        name: publish helm chart to acr
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - uses: actions/checkout@v4
              name: checkout repo

            - name: install helm
              uses: azure/setup-helm@v4.2.0
              id: install

            - name: login to acr using helm
              run: |
                  echo ${{ secrets.AZURE_CLIENT_SECRET }} | helm registry login holon.azurecr.io --username ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

            - name: save helm chart to local registry
              run: |
                  helm chart save $/charts/hallo-azure/ ${{ secrets.AZURE_URL }}/hallo-azure-helmchart:${{ env.COMMIT_SHORT_SHA }}

            - name: publish chart to acr
              run: |
                  helm chart push ${{ secrets.AZURE_URL }}/hallo-azure-helmchart:latest