name: Push Helm chart to ACR

on:
    push:
        branches:
            - master

jobs:
    build:
        name: publish helm chart to acr
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              name: checkout repo

            - name: Set environment variables
              id: set-variables
              run: |
                echo "VERSION=$(yq -r .version ./charts/hallo-azure/Chart.yaml)" >> "$GITHUB_OUTPUT"     

            - name: install helm
              uses: azure/setup-helm@v4.2.0
              id: install

            - name: login to acr using helm
              run: |
                  echo ${{ secrets.AZURE_CLIENT_SECRET }} | helm registry login ${{ secrets.AZURE_URL }} --username ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

            - name: save helm chart and publish
              id: build-push
              run: |
                  helm package ./charts/hallo-azure --version ${{ steps.set-variables.outputs.VERSION }}
                  helm push ./hallo-azure-${{ steps.set-variables.outputs.VERSION }}.tgz oci://${{ secrets.AZURE_URL }}/charts
