name: Is version changed

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Semantic versioning job
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Is helm chart version changed
              id: is-chart-changed
              run: |
                  if git diff ${{ github.event.before }} ${{ github.event.after }} ./charts/hallo-azure/Chart.yaml | grep -q '+version'; then
                    echo "chart_version_changed=true" >> $GITHUB_ENV
                  else
                    echo "chart_version_changed=false" >> $GITHUB_ENV
                  fi 

            - name: Use custom action to check chart version
              id: check_version
              uses: amb-adam-budych-rd/hallo-github/actions/check-helm-chart-version-changed@v7
              with:
                chart_path: './charts/hallo-azure/Chart.yaml'

            - name: Debug changes
              run: |
                echo "inside check: ${{ env.chart_version_changed }}"
                echo "separate check: ${{ steps.check_version.outputs.is_chart_version_changed }}"

            - name: Run inside condition command
              if: env.chart_version_changed == 'true'
              run: echo chart version changed and build executed

            - name: Run separate condition command
              if: steps.check_version.outputs.is_chart_version_changed == 'true'
              run: echo chart version changed and build executed
