name: Is version changed

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Semantic versioning job
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Is helm chart version changed
              id: is-chart-changed
              run: |
                  if git diff ${{ github.event.before }} ${{ github.event.after }} ./charts/hallo-azure/Chart.yaml | grep -q 'version'; then
                    echo "chart_version_changed=true" >> $GITHUB_ENV
                  else
                    echo "chart_version_changed=false" >> $GITHUB_ENV
                  fi 

            - name: Debug changes
              run: |
                echo "${{ env.chart_version_changed }}"

            - name: Run condition  command
              if: env.chart_version_changed == 'true'
              run: echo chart version changed and build executed
                
