name: Is version changed

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Semantic versioning job
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Get changes
              run: git diff ${{ github.event.before }} ${{ github.event.after }} ./charts/hallo-azure/Chart.yaml | grep -q 'version' && echo chart version changed
                
